django_app/config/urls.py
from django.conf.urls import url, include
from django.contrib import admin

import post
from post import views, urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^post/', include('post.urls')),


]

django_app/post/urls.py
from django.conf.urls import url

from post import views

app_name = 'post'
urlpatterns = [
    url(r'^$', views.post_list, name='post_list'),

    url(r'^(?P<post_pk>\d)/delete/$', views.post_delete, name='post_delete'),

    url(r'^(?P<post_pk>\d)/modify/$', views.post_modify, name='post_modify'),

    url(r'^create/$', views.post_create, name='post_create'),

]

django_app/post/models.py
from django.db import models
from django.contrib.auth.models import User


class Post(models.Model):
    author = models.ForeignKey(User)
    comment = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)
    modify_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.comment

django_app/post/views.py
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.shortcuts import render, redirect

# Create your views here.
from post.models import Post


def post_list(request):
    posts = Post.objects.all()
    context = {
        'posts': posts
    }
    return render(request, 'post_list.html', context)


def post_delete(request, post_pk):
    post = Post.objects.get(pk=post_pk)
    if request.method == 'POST':
        post.delete()
        return redirect('post:post_list')



def post_modify(request, post_pk):
    post = Post.objects.get(pk=post_pk)
    post.save()

    return render(request, 'post_modify.html')

def post_create(request):
    user=User.objects.first()
    comment=request.POST['comment']
    Post.objects.create(
        author=user,
        comment=comment,
    )
    return render(request, 'post_create.html')

django_app/templates/post_create.html
<!doctype html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
<form action="" method="POST">
    {% csrf_token %}
    <label for="">댓글:</label>
    <input type="text" name="comment">
</form>
</body>
</html>

django_app/templates/post_list.html
<!doctype html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <a href="{% url 'post:post_create' %}">글쓰기</a>
    {% for post in posts %}
        <ul>
            <li>
                {{ post }}
                <a href="{% url 'post:post_modify' post_pk=post.pk %}">수정하기</a>
                <form action="{% url 'post:post_delete' post_pk=post.pk %}" method="POST">
                    {% csrf_token %}
                    <a href="">삭제하기</a>
                </form>
            </li>

        </ul>
    {% endfor %}
</body>
</html>

django_app/templates/post_modify.html
<!doctype html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <h3>포스트 수정</h3>
    <form action="" method="POST">
        <label for="">댓글: </label>
        <input type="text">
    </form>
</body>
</html>